<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\Animations\application-started.mp4" />
		<None Remove="Assets\Animations\code-restore-tab-activated.mp4" />
		<None Remove="Assets\Animations\code-masking-tab-activated.mp4" />
		<None Remove="Assets\Animations\masking-started.mp4" />
		<None Remove="Assets\Animations\error-occurred.mp4" />

		<Content Include="Assets\Animations\application-started.mp4">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		<Content Include="Assets\Animations\code-restore-tab-activated.mp4">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		<Content Include="Assets\Animations\code-masking-tab-activated.mp4">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		<Content Include="Assets\Animations\masking-started.mp4">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		<Content Include="Assets\Animations\error-occurred.mp4">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

</Project>