<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\Animations\ClassicVideo\**\*.*" />
		<None Remove="Assets\Animations\MaskState\**\*.*" />

		<Content Include="Assets\Animations\ClassicVideo\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		<Content Include="Assets\Animations\MaskState\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Assets\Animations\MaskState\Transitions\" />
	</ItemGroup>

</Project>