<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp"
		                  Version="5.6.0" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Assets\Animations\ClassicVideo\**\*.*" />
		<None Remove="Assets\Animations\MaskState\**\*.*" />
		<None Remove="Assets\Brand\maskod-logo.png" />

		<Resource Include="Assets\Brand\maskod-logo.png" />

		<Content Include="Assets\Animations\ClassicVideo\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>

		<Content Include="Assets\Animations\MaskState\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Assets\Animations\MaskState\Transitions\" />
		<Folder Include="Assets\Brand\" />
	</ItemGroup>

</Project>